mes_meta: # SE DEBE MODIFICAR CADA MES CUIDADO!!!!
   'ABR 2025'

filtro_metas_final:
  cod_vendedor:  # vendedores genericos
    - "#"
    - 3828
    - 2991
    - 2991
    - 2996
    - 2951
    - 2991
    - 3828
    - 2992
    - 2997
    - 2995

  cod_jefe_ventas:
   - 3692 # ANDRES BAUTISTA
   - 2973 # CARLOS NIETO 
   - 3150 # JAIME ARBOLEDA
   - 16695 #HENRY PAEZ
  

listado_insumos:
  - 'Clientes_activos_Dir_Ind.xlsx' #0
  - 'driver_Fuerza_portafolio.xlsx' #1
  - 'drivers_transformados.xlsx' #2
  - 'PortafolioInfaltable.xlsx' #3
  - 'maestra_socios.xlsx' #4
  - 'base.xlsx' # 5 promos
  

tablas_bd_pi_metas:
  - Ventas # 0
  - tabla_fuerza #1
  - tabla_portafolio #2
  - tabla_portafolio_au_td #3
  - tabla_portafolio_bn_ce #4
  - tabla_tipologias #5
  - universo_directa #6
  - universo_indirecta #7
  - maestra_socios #8

columnas_universos_dir: ## columnas de la tabla universo_directa
  Cód. Cliente : cliente_clave
  Nombre Cliente : nombre_cliente
  Cód. Vendedor : cod_vendedor
  Bloq. Pedido : bloque_pedido
  Cód. Jefe Vtas: cod_jefe_ventas
  Nombre Jefe Ventas: nombre_jefe_ventas

lista_universo_ind: ## columnas de la tabla universo_indirecta
  r_id_agente_comercial : clave_agente
  cv_nombre_agente_comercial : nombre_agente
  r_id_vendedor : cod_vendedor
  r_id_cliente : codigo_ecom
  Cod_CRM: cliente_clave
  Tipologia Aj: tipologia
  Cod_jefe : cod_jefe_ventas
  Nombre_jefe : nombre_jefe_ventas
  Fuerzas en el rutero : fuerza
  Nom_oficina : oficina_ventas

driver_fuerza_portafolio:
  driver_fuerza:
    cod_portafolio : cod_portafolio
    codigo_Fuerza : codigo_fuerza
  driver_portafolio:
    cod_material : cod_material
    cod_portafolio : cod_portafolio

columnas_maestra_socios:
    Cod_Cliente : cod_cliente_ecom_sap
    CRM Indirecta : cliente_clave
    Cod_Agente : clave_agente
    Nom_Agente : nombre_agente
    Socio : socio

driver_transformados:
  tipologia:
    clave_tipologia: clave_tipologia
    tipologia : tipologia
    clave_canal_trans : clave_canal_trans
    canal_trans : canal_trans
    clave_sub_canal_trans: clave_sub_canal_trans
    sub_canal_trans: sub_canal_trans
    cod_segmento: clave_segmento
    segmento_trans: segmento_trans

  segmento_valor:
    Pequeño: AA
    Mediano : AB
    Grande: AC
  
estrato:
  'Sin asignar' : Estrato Bajo
  'Sin Asignar' : Estrato Bajo
  'Sin Estrato' : Estrato Bajo
  'Estrato 1': Estrato Bajo
  'Estrato 2' : Estrato Bajo
  'Estrato 3' : Estrato Bajo
  'Estrato 4' : Estrato Alto
  'Estrato 5' : Estrato Alto
  'Estrato 6' : Estrato Alto

codigos_oficinas:
  'R Oficina Central' : '00'
  'R Bogota Norte' : '11'
  'R Bucaramanga' : '12'
  'R Cali' : '13'
  'R Ibague': '14'
  'R Medellin' : '16'
  'R Altillano': '17'
  'R Barranquilla': '20'
  'R Cartagena': '23'
  'R Pereira': '25'
  'R General Nacional': 'R61'
  'Sin asignar': '#'

portafolio:
  portafolio_au_td:
    Oficina de ventas: oficina_ventas
    Canal Transformado : canal_trans
    Sub Canal Transformado : sub_canal_trans
    Segmento Transformado : segmento_trans
    Tipología / Segmento 3 : tipologia
    Material Meta : material_meta
    Nombre Material Meta : nombre_material_meta
    Categoría : categoria
    Sub Categoría : sub_categoria
    Línea : linea
    Marca : marca
    Segmento de Valor CRM : segmento_valor
    Estrato : estrato
    Material Impactos : material_impactos
    Nombre Material Impactos : nombre_material_impactos
    Excluir de Meta : excluir_metas
    Innovación : innovacion

  portafolio_bn_ce:
    Oficina de ventas : oficina_ventas
    Canal Transformado : canal_trans
    Sub Canal Transformado : sub_canal_trans
    Segmento Transformado : segmento_trans
    Tipología / Segmento 3 : tipologia
    Material Meta : material_meta
    Nombre Material Meta : nombre_material_meta
    Categoría : categoria
    Sub Categoría : sub_categoria
    Línea : linea
    Marca : marca
    Material Impactos : material_impactos
    Nombre Material Impactos : nombre_material_impactos
    Excluir de Meta : excluir_metas
    Innovación : innovacion

columnas_ventas:
  Tipo de Venta - Texto : [tipo_venta,str]
  Oficina de ventas - Clave : [clave_oficina_ventas,str]
  Oficina de ventas : [oficina_ventas,str]
  Agente Comercial - Clave : [clave_agente,str]
  Agente Comercial - Texto de longitud media : [nombre_agente,str]
  Tipología / Segmento 3 - Clave : [clave_tipologia,str]
  Tipología / Segmento 3 : [tipologia,str]
  Grupo de clientes 4 - Clave : [clave_segmento_vital,str]
  Grupo de clientes 4 : [segmento_vital,str]
  Cliente - Clave : [cliente_clave,str]
  Nombre Comercial : [nombre_cliente,str]
  Código ECOM : [cod_ecom,str]
  Código Municpio : [cod_municipio,str]
  Grupo de clientes 5 - Clave : [cod_grupo_cliente_5_orig,str]
  Grupo de clientes 5 : [grupo_cliente_5_orig,str]
  Estrato : [estrato_original,str]
  Segmento de Valor CRM - Clave : [cod_segmento_valor,str]
  Segmento de Valor CRM : [segmento_valor,str]
  Jefe de Ventas Vendedor Dinámico - Clave : [cod_jefe_ventas,str]
  Representante de Ventas Dinámico - Clave : [cod_vendedor,str]
  Representante de Ventas Dinámico : [nombre_vendedor,str]
  Sector - Clave : [clave_sector,str]
  Sector: [sector,str]
  Categoría (0MATERIAL__ZCATGORIA) - Clave : [clave_categoria,str]
  Categoría (0MATERIAL__ZCATGORIA) : [categoria,str]
  Sub Categoría - Clave : [clave_sub_categoria,str]
  Sub Categoría : [sub_categoria,str]
  Línea - Clave : [linea_clave,str]
  Línea : [linea,str]
  Marca - Clave : [clave_marca,str]
  Marca : [marca,str]
  Material - Clave : [cod_material,str]
  Material : [material,str]
  Año/Mes : [anio_mes,str]
  Venta Neta Mes Actual $ : [venta_cop,int]
  Venta Neta Mes Actual UN : [venta_un,float]
  Venta Neta Mes Actual KG : [venta_kg,float]

nombres_mod_recom_AU_TD:
  - PRODUCT_ID
  - SALES_OFFICE_ID
  - CUST_TYPE_ID 
  - DIST_CHANNEL_TRANS
  - SUB_DIST_CHAN_TRANS 
  - TIPOL_TRANS 
  - CUST_GROUP5
  - STRATUM_GROUPED 
  - SECTOR_ID

nombres_mod_recom_bn_ce:
  - PRODUCT_ID
  - SALES_OFFICE_ID
  - CUST_TYPE_ID 
  - DIST_CHANNEL_TRANS
  - SUB_DIST_CHAN_TRANS 
  - TIPOL_TRANS 
  - SECTOR_ID